spring.application.name=protoserv

spring.datasource.url=jdbc:mysql://localhost:3306/protoserv_db
spring.datasource.username=admin
spring.datasource.password=protoserv

spring.flyway.url=jdbc:mysql://localhost:3306/protoserv_db
spring.flyway.user=admin
spring.flyway.password=protoserv

api.security.token.secret=${JWT_SECRET:protoserv-chave-secreta-muito-longa-e-segura-para-assinatura-jwt-2026}
api.default.admin.email=${DEFAULT_EMAIL:admin@protoserv.com}
api.default.admin.senha=${DEFAULT_SENHA:Admin123!}


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=e4bb5c44ef1ce7
spring.mail.password=3e2dc55c060b5c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true